version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring
    app:
    build:
      context: .  # Путь к вашему проекту
    container_name: devsecops-app
    environment:
      - ENV=production  # Добавить переменные окружения, если нужно
    ports:
      - "5000:5000"  # Прокси порта приложения
    volumes:
      - .:/app  # Монтируем код
    networks:
      - monitoring
    depends_on:
      - postgres  # Зависит от базы данных PostgreSQL
      - sonarqube  # Зависит от SonarQube

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  postgres_data:
  sonarqube_data:
  grafana_data:

