
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  bandit:
    image: python:3.12
    container_name: bandit
    volumes:
      - ./:/src
    working_dir: /src
    command: >
      bash -c "
        pip install --no-cache-dir bandit &&
        mkdir -p /src/reports &&
        bandit -r src/ -f json -o /src/reports/bandit-report.json || true
      "

  pip-audit:
    image: python:3.12
    container_name: pip-audit
    volumes:
      - ./:/src
    working_dir: /src
    command: >
      bash -c "
        pip install --no-cache-dir pip-audit &&
        mkdir -p /src/reports &&
        pip-audit --format=json --output=/src/reports/pip-audit-report.json || true
      "

  trivy:
    image: aquasec/trivy:0.49.1
    container_name: trivy
    volumes:
      - ./:/src
    working_dir: /src
    command: >
      trivy fs --scans vuln,config -f sarif -o /src/reports/trivy-report.sarif /src || true

  gitleaks:
    image: ghcr.io/gitleaks/gitleaks:v8.24.2
    container_name: gitleaks
    volumes:
      - ./:/src
    working_dir: /src
    command: >
      detect --source=/src --report-format=sarif --report-path=/src/reports/gitleaks-report.sarif || true
      
volumes:
  grafana-storage:
