name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit

          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_linux_amd64.tar.gz
          tar -xvf trivy_linux_amd64.tar.gz
          sudo mv trivy /usr/local/bin/

          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O gitleaks
          chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/

      - name: Run Bandit (SAST)
        run: bandit -r src/ || true  # Чтобы не прерывало выполнение при ошибках

      - name: Run Pip Audit (Dependency Scan)
        run: pip-audit || true

      - name: Run Trivy on dependencies
        run: trivy fs --scanners vuln,config . || true

      - name: Run Gitleaks (Secrets Scan)
        run: gitleaks detect -v || true
