name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  security-events: write
  contents: read
  pull-requests: read

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --no-cache-dir bandit pip-audit trivy

      - name: Run Bandit (SAST)
        run: |
          bandit -r src/ -f sarif -o bandit-report.sarif || true

      - name: Run Pip Audit (Dependency Scan)
        run: |
          pip-audit --format=sarif --output=pip-audit-report.sarif || true

      - name: Run Trivy on dependencies
        run: |
          trivy fs --scanners vuln,config -f sarif -o trivy-report.sarif .

      - name: Run Gitleaks (Secrets Scan) via Docker
        run: |
          docker run --rm -v $(pwd):/src ghcr.io/gitleaks/gitleaks:v8.24.2 detect -s /src -v --report-format=sarif --report-path=/src/gitleaks-report.sarif || true

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.sarif
            pip-audit-report.sarif
            trivy-report.sarif
            gitleaks-report.sarif

      - name: Upload Bandit report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-report.sarif

      - name: Upload Pip Audit report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit-report.sarif

      - name: Upload Trivy report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif

      - name: Upload Gitleaks report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-report.sarif
