name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --no-cache-dir bandit pip-audit

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/
          trivy --version

      - name: Install Gitleaks
        run: |
          wget --retry-connrefused --waitretry=5 --timeout=30 -t 3 -q https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O gitleaks
          if [ ! -f gitleaks ]; then
            echo "Failed to download Gitleaks binary" >&2
            exit 1
          fi
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version

      - name: Run Bandit (SAST)
        run: |
          bandit -r src/ || true  # Ensure Bandit runs without failing the workflow

      - name: Run Pip Audit (Dependency Scan)
        run: |
          pip-audit || true

      - name: Run Trivy on dependencies
        run: |
          trivy fs --scanners vuln,config .

      - name: Run Gitleaks (Secrets Scan)
        run: |
          gitleaks detect -v || true