name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write
  contents: read
  pull-requests: read

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установить Python и необходимые зависимости
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Шаг 3: Установить зависимости для проверки безопасности
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --no-cache-dir bandit pip-audit

      # Шаг 4: Установить Trivy (обновленная версия установки)
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/
          trivy --version  # Проверим установку

      # Шаг 5: Запуск Bandit для анализа кода (SAST) с форматом SARIF
      - name: Run Bandit (SAST)
        run: |
          bandit -r src/ -f sarif -o bandit-report.sarif || true

      # Шаг 6: Запуск Pip Audit для проверки зависимостей
      - name: Run Pip Audit (Dependency Scan)
        run: |
          pip-audit --format=sarif --output=pip-audit-report.sarif || true

      # Шаг 7: Запуск Trivy для проверки уязвимостей
      - name: Run Trivy on dependencies
        run: |
          trivy fs --scanners vuln,config -f sarif -o trivy-report.sarif . || true

      # Шаг 8: Запуск Gitleaks для поиска секретных ключей
      - name: Run Gitleaks (Secrets Scan) via Docker
        run: |
          docker run --rm -v $(pwd):/src ghcr.io/gitleaks/gitleaks:v8.24.2 detect -s /src -v --report-format=sarif --report-path=/src/gitleaks-report.sarif || true

      # Шаг 9: Проверка существования отчетов (для отладки)
      - name: List generated files
        run: |
          ls -lah

      # Шаг 10: Загружаем отчеты как артефакты
      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.sarif
            pip-audit-report.sarif
            trivy-report.sarif
            gitleaks-report.sarif

      # Шаг 11: Загружаем отчеты в GitHub Security Tab (SARIF формат)
      - name: Upload Bandit report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-report.sarif

      - name: Upload Pip Audit report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit-report.sarif

      - name: Upload Trivy report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif

      - name: Upload Gitleaks report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-report.sarif
