name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Кешируем пакеты Python

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit
  
          # Устанавливаем Trivy вручную (так как apt-репозиторий не поддерживает Ubuntu 24.04)
          wget -qO trivy.tar.gz https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar -xzf trivy.tar.gz
          sudo mv trivy /usr/local/bin/
  
          # Устанавливаем Gitleaks вручную
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/

      - name: Run Bandit (SAST)
        run: bandit -r src/
        continue-on-error: true  # Не прерываем выполнение при ошибках

      - name: Run Pip Audit (Dependency Scan)
        run: pip-audit
        continue-on-error: true

      - name: Run Trivy on dependencies
        run: trivy fs --scanners vuln,config .
        continue-on-error: true

      - name: Run Gitleaks (Secrets Scan)
        run: gitleaks detect -v
        continue-on-error: true
