name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  security-events: write
  contents: read
  pull-requests: read

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --no-cache-dir bandit pip-audit

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/
          trivy --version

      - name: Run Bandit (SAST)
        run: |
          bandit -r src/ -f sarif -o $(pwd)/bandit-report.sarif || echo "Bandit failed"
          ls -lah $(pwd)

      - name: Run Pip Audit (Dependency Scan)
        run: |
          pip-audit --format=sarif --output=$(pwd)/pip-audit-report.sarif || echo "Pip Audit failed"
          ls -lah $(pwd)

      - name: Run Trivy on dependencies
        run: |
          trivy fs --scanners vuln,config -f sarif -o $(pwd)/trivy-report.sarif . || echo "Trivy failed"
          ls -lah $(pwd)

      - name: Run Gitleaks (Secrets Scan) via Docker
        run: |
          docker run --rm -v $(pwd):/src ghcr.io/gitleaks/gitleaks:v8.24.2 detect -s /src -v --report-format=sarif --report-path=/src/gitleaks-report.sarif || echo "Gitleaks failed"
          ls -lah $(pwd)

      - name: Verify that reports exist
        run: |
          ls -lah $(pwd)
          test -f bandit-report.sarif && echo "Bandit report exists" || echo "Bandit report MISSING"
          test -f pip-audit-report.sarif && echo "Pip Audit report exists" || echo "Pip Audit report MISSING"
          test -f trivy-report.sarif && echo "Trivy report exists" || echo "Trivy report MISSING"
          test -f gitleaks-report.sarif && echo "Gitleaks report exists" || echo "Gitleaks report MISSING"

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.sarif
            pip-audit-report.sarif
            trivy-report.sarif
            gitleaks-report.sarif

      - name: Upload SARIF reports to GitHub Security Tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: band_
